<template>
  <div class="pages">
    <el-table :data="tableData" border :fit="true">
      <el-table-column type="selection" width="80" fixed></el-table-column>
      <el-table-column label="姓名" prop="name" width="100" fixed></el-table-column>
      <el-table-column label="性别" prop="gender" width="100" fixed></el-table-column>
      <el-table-column label="地区" prop="location" width="100" fixed></el-table-column>
      <el-table-column label="工作状态" prop="job_state" width="100"></el-table-column>
      <el-table-column label="户籍" prop="native" width="100"></el-table-column>
      <el-table-column label="意向工作" prop="intent_job" width="100"></el-table-column>
      <el-table-column label="公司名称" prop="work_com_name" width="100"></el-table-column>
      <el-table-column label="工作地址" prop="work_address" width="100"></el-table-column>
      <el-table-column label="毕业院校" prop="education_school" width="100"></el-table-column>
      <el-table-column label="专业" prop="education_major" width="100"></el-table-column>
      <el-table-column label="婚姻情况" prop="marriage" width="100"></el-table-column>
      <el-table-column label="最近更新" prop="edit_time" width="100"></el-table-column>
      <el-table-column label="创建人" prop="create_user" width="100"></el-table-column>
    </el-table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      tableData: [
    {
        "_id":{
            "$oid":"5be009fb5dbd0954e999ce3b"
        },
        "name":"史可可",
        "bad_record":0,
        "bad_record_list":[

        ],
        "tag_list":[

        ],
        "gender":"男",
        "location":"浙江-宁波",
        "job_state":"随时",
        "mobile":"15168524220",
        "email":"",
        "native":"浙江-宁波",
        "house":"",
        "card_num":"",
        "age":49,
        "skill_list":[

        ],
        "intent_job_location":"",
        "intent_salary_type":-1,
        "intent_min_salary":0,
        "intent_max_salary":0,
        "intent_job":"销售",
        "intent_com":"",
        "intent_power":"",
        "work_year":"7年",
        "work_year_code":7,
        "dimission_period":"",
        "work_is_job":"否",
        "work_com_name":"好公司一",
        "work_com_id":{
            "$oid":"5bd6e4f6e138236e7124c765"
        },
        "work_address":"上海市-上海市-黄浦区",
        "work_industry":"",
        "work_industry_level":"",
        "work_position":"新岗位",
        "work_position_level":"",
        "work_salary_type":"",
        "work_salary":"",
        "project_name":"",
        "education_degree":"大专",
        "education_degree_code":4,
        "education_school":"象山技工学校",
        "education_major":"计算机应用",
        "education_is_read":"否",
        "education_is_full_time":"否",
        "education_school_is_985":"",
        "education_school_is_211":"",
        "train_school":"",
        "train_course":"",
        "marriage":"未婚",
        "couple_position":"",
        "couple_com":"",
        "children":"",
        "relation_time":"2019-05-10",
        "relation_time_int":1557417600,
        "edit_time":"2019-05-21",
        "edit_time_int":1558420905,
        "remark_list_name":"",
        "position_action":"未加入",
        "position_action_code":"",
        "position_action_list":[

        ],
        "team_position_action":"未加入",
        "team_position_action_code":"",
        "team_position_action_list":"",
        "my_position_action":"未加入",
        "my_position_action_code":"",
        "my_position_action_list":"",
        "my_order":"",
        "my_position":"",
        "create_type":"",
        "add_time":"2018-11-06",
        "create_user":"宁佐飞",
        "create_email":"",
        "look_time":"",
        "is_look":0,
        "attention_time":"",
        "attention":0,
        "work_list":[
            {
                "begin":"2018-11",
                "end":"至今",
                "com_name":"好公司一",
                "department":"",
                "position":"新岗位",
                "position_level":0,
                "work_address":"上海市-上海市-黄浦区",
                "work_address_code":10000100,
                "description":"",
                "salary_type":"",
                "salary":"",
                "salary_detail":"",
                "salary_pay":"",
                "industry":null,
                "industry_code":1,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":null,
                "com_type":null,
                "com_type_code":3,
                "quit_reason":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2018-11",
                "end":"",
                "com_name":"新公司一",
                "industry":"",
                "industry_code":1,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"",
                "com_type_code":0,
                "com_type":"",
                "department":"",
                "position":"测试工程师",
                "position_level":"",
                "description":"",
                "quit_reason":"",
                "work_address":"上海市-上海市-黄浦区",
                "work_address_code":10000100,
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2018-11",
                "end":"",
                "com_name":"十一月八八",
                "industry":"",
                "industry_code":1,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"",
                "com_type_code":5,
                "com_type":"",
                "department":"环球科技",
                "position":"奥特曼",
                "position_level":"",
                "description":"",
                "quit_reason":"",
                "work_address":"广东省-深圳市-罗湖区",
                "work_address_code":14020100,
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2016-01",
                "end":"2018-02",
                "com_name":"宁波迪斯凯家居用品有限公司",
                "industry":"家具/家电/玩具/礼品",
                "industry_code":"",
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"50",
                "com_type_code":"",
                "com_type":"民营",
                "department":"",
                "position":"销售代表",
                "position_level":"",
                "description":"通过展会收集客户资料,拜访客户,达成合作",
                "quit_reason":"",
                "work_address":"",
                "work_address_code":"",
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2013-10",
                "end":"2015-06",
                "com_name":"上海银行",
                "industry":"银行",
                "industry_code":"",
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"10000",
                "com_type_code":"",
                "com_type":"上市公司",
                "department":"信用卡部门",
                "position":"销售代表",
                "position_level":"",
                "description":"信用卡的推销",
                "quit_reason":"",
                "work_address":"",
                "work_address_code":"",
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2011-12",
                "end":"2013-09",
                "com_name":"宁波国际物流",
                "industry":"交通/运输/物流",
                "industry_code":"",
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"50",
                "com_type_code":"",
                "com_type":"民营",
                "department":"",
                "position":"销售",
                "position_level":"",
                "description":"提高订舱,报关等等",
                "quit_reason":"",
                "work_address":"",
                "work_address_code":"",
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            }
        ],
        "education_list":[
            {
                "begin":"2005-09",
                "end":"2009-06",
                "degree":"大专",
                "degree_code":4,
                "school":"象山技工学校",
                "major":"计算机应用",
                "major_desc":"",
                "is_full_time":null,
                "attach_file":[

                ]
            }
        ],
        "train_list":[

        ],
        "project_list":[

        ],
        "work_salary_str":"",
        "intent_salary_str":""
    },
    {
        "_id":{
            "$oid":"5be00a3e5dbd0954e999ce3e"
        },
        "name":"董彬",
        "bad_record":0,
        "bad_record_list":[

        ],
        "tag_list":[

        ],
        "gender":"男",
        "location":"北京",
        "job_state":"离职看机会",
        "mobile":"13333358468",
        "email":"iosbin@sohu.com",
        "native":"上海-黄浦区",
        "house":"",
        "card_num":"",
        "age":49,
        "skill_list":[
            {
                "date":"2018-11-19",
                "name":"2010.06 大学英语四级",
                "level":"",
                "attach_file":[

                ]
            },
            {
                "date":"2018-11-19",
                "name":"CocoaPods",
                "level":"熟练",
                "attach_file":[

                ]
            },
            {
                "date":"2018-11-19",
                "name":"C语言",
                "level":"熟练",
                "attach_file":[

                ]
            },
            {
                "date":"2018-11-19",
                "name":"FMDB",
                "level":"熟练",
                "attach_file":[

                ]
            },
            {
                "date":"2018-11-19",
                "name":"JSON",
                "level":"熟练",
                "attach_file":[

                ]
            },
            {
                "date":"2018-11-19",
                "name":"MVC",
                "level":"熟练",
                "attach_file":[

                ]
            },
            {
                "date":"2018-11-19",
                "name":"XML",
                "level":"",
                "attach_file":[

                ]
            },
            {
                "date":"2018-11-19",
                "name":"英语",
                "level":"熟练",
                "attach_file":[

                ]
            },
            {
                "date":"",
                "name":"Git",
                "level":"熟练",
                "attach_file":[

                ]
            }
        ],
        "intent_job_location":"上海-黄浦区，北京",
        "intent_salary_type":-1,
        "intent_min_salary":0,
        "intent_max_salary":0,
        "intent_job":"手机软件开发工程师,移动互联网开发,软件工程师,软件研发工程师,互联网软件工程师",
        "intent_com":"",
        "intent_power":"",
        "work_year":"3年",
        "work_year_code":3,
        "dimission_period":"",
        "work_is_job":"否",
        "work_com_name":"十一月二十六",
        "work_com_id":{
            "$oid":"5bfe6777e1382368fb6855c2"
        },
        "work_address":"广东省-深圳市-罗湖区",
        "work_industry":"",
        "work_industry_level":"",
        "work_position":"JAVA",
        "work_position_level":"",
        "work_salary_type":"",
        "work_salary":"",
        "project_name":"肩颈健康百科(已上线)",
        "education_degree":"本科",
        "education_degree_code":5,
        "education_school":"河北科技大学",
        "education_major":"计算机科学与技术",
        "education_is_read":"否",
        "education_is_full_time":"否",
        "education_school_is_985":"",
        "education_school_is_211":"",
        "train_school":"",
        "train_course":"",
        "marriage":"未婚",
        "couple_position":"",
        "couple_com":"",
        "children":"",
        "relation_time":"",
        "relation_time_int":0,
        "edit_time":"2019-05-21",
        "edit_time_int":1558420735,
        "remark_list_name":"",
        "position_action":"未加入",
        "position_action_code":"",
        "position_action_list":[

        ],
        "team_position_action":"未加入",
        "team_position_action_code":"",
        "team_position_action_list":"",
        "my_position_action":"未加入",
        "my_position_action_code":"",
        "my_position_action_list":"",
        "my_order":"",
        "my_position":"",
        "create_type":"",
        "add_time":"2018-11-06",
        "create_user":"宁佐飞",
        "create_email":"",
        "look_time":"",
        "is_look":0,
        "attention_time":"",
        "attention":0,
        "work_list":[
            {
                "begin":"2018-11",
                "end":"至今",
                "com_name":"十一月二十六",
                "department":"研发部",
                "position":"JAVA",
                "position_level":0,
                "work_address":"广东省-深圳市-罗湖区",
                "work_address_code":14020100,
                "description":"",
                "salary_type":"",
                "salary":"",
                "salary_detail":"",
                "salary_pay":"",
                "industry":null,
                "industry_code":1,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":null,
                "com_type":null,
                "com_type_code":0,
                "quit_reason":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2018-11",
                "end":"",
                "com_name":"新公司一",
                "industry":"",
                "industry_code":1,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"",
                "com_type_code":0,
                "com_type":"",
                "department":"",
                "position":"测试工程师",
                "position_level":"",
                "description":"",
                "quit_reason":"",
                "work_address":"上海市-上海市-黄浦区",
                "work_address_code":10000100,
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2013-06",
                "end":"2015-12-01",
                "com_name":"河北红珊瑚科技有限公司",
                "industry":"互联网/电子商务",
                "industry_code":"",
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"20-99人",
                "com_type_code":"",
                "com_type":"民营",
                "department":"",
                "position":"iOS开发工程师",
                "position_level":"",
                "description":"1. 负责iOS手机客户端及其应用软件的设计、开发;2. 参与软件测试及维护,配合策划及美术人员优化产品功能、提高用户可操作性;3. 参与分析业务需求,系统设计和开发;4. 根据产品需求完成简易框架,模块设计,编码,设计等工作;5. 学习和研究新技术以满足产品的需求。",
                "quit_reason":"",
                "work_address":"",
                "work_address_code":"",
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2012-02",
                "end":"2013-05-01",
                "com_name":"石家庄天嘉科技开发有限公司",
                "industry":"互联网/电子商务",
                "industry_code":"",
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"20-99人",
                "com_type_code":"",
                "com_type":"民营",
                "department":"",
                "position":"运维工程师",
                "position_level":"",
                "description":"网络维护",
                "quit_reason":"",
                "work_address":"",
                "work_address_code":"",
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            }
        ],
        "education_list":[
            {
                "begin":"2008-09",
                "end":"2012-06-01",
                "degree":"本科",
                "degree_code":5,
                "school":"河北科技大学",
                "major":"计算机科学与技术",
                "major_desc":"",
                "is_full_time":1,
                "attach_file":[

                ]
            }
        ],
        "train_list":[

        ],
        "project_list":[
            {
                "begin":"2015-10",
                "end":"2015-12",
                "pro_name":"肩颈健康百科(已上线)",
                "pro_describe":"介绍肩颈健康的相关知识和资讯,通过算法猜出您的兴趣,向您推荐最适合您的肩颈健康知识,同时您也可以向医生进行咨询。",
                "duty_describe":"全部功能实现",
                "is_leader":0,
                "is_progress":0
            },
            {
                "begin":"2015-06",
                "end":"2015-10",
                "pro_name":"邯郸电商生活圈(已上线)",
                "pro_describe":"是一个整合邯郸本地生活、电商资源、园区运营、创业服务、娱乐、交友集一体的综合性APP,旨在打造邯郸本地第一家细分电商领域专家!",
                "duty_describe":"软件架构的搭建,编写网络框架;参与前期需求文档的整理,整体架构的划分;负责圈子好友模块及论坛模块的编程;参与项目后期的测试,收尾",
                "is_leader":0,
                "is_progress":0
            },
            {
                "begin":"2015-02",
                "end":"2015-05",
                "pro_name":"购物党(已上线)",
                "pro_describe":"一款可以比较同款商品在主流网店的价格,汇总全网处于最低价的商品,促销活动汇总全网给力的最新最热的满减活动",
                "duty_describe":"负责软件架构的搭建,基础功能类封装,部分控件封装;编写网络框架,逻辑跳转控制;对UI的图片制试,开发具体功能模块;设计数据模型与数据解析;",
                "is_leader":0,
                "is_progress":0
            },
            {
                "begin":"2014-09",
                "end":"2014-12",
                "pro_name":"石家庄生活平台(已上线)",
                "pro_describe":"一款集城市热点、娱乐、购物、休闲、旅游及美食等为一体的手机客户端,全面展示石家庄当地的热点信息、民生起居、旅游景点等相关行业信息。",
                "duty_describe":"负责与客户确认需求,确定接口;负责软件架构的搭建,编写网络框架;负责导航和个人中心界面功能的实现;负责在线支付功能的实现;负责前期需求文档的整理,整体架构的划分;",
                "is_leader":0,
                "is_progress":0
            },
            {
                "begin":"2014-05",
                "end":"2014-07",
                "pro_name":"求攻略自由行(已上线)",
                "pro_describe":"最受好评的自由行神器,旅行结伴出游必备;最强大的旅行指南,自助游、国内游、出境游、让你的旅行一步到位,轻松搞定;当地人陪你玩:不再担心陌生环境,旅行私导,包车,一日游,全程为你服务;最愉快的聊天社区,分享美景美食,结伴帅哥美女,各路旅行动态、实时交流零距离",
                "duty_describe":"实现首页图片轮播;天气预报功能;切换城市目的地功能;导航等局部UI界面优化",
                "is_leader":0,
                "is_progress":0
            }
        ],
        "work_salary_str":"",
        "intent_salary_str":""
    },
    {
        "_id":{
            "$oid":"5be00deb94ca745e47a0d4a2"
        },
        "name":"朱小军",
        "bad_record":0,
        "bad_record_list":[

        ],
        "tag_list":[

        ],
        "gender":"男",
        "location":"广东-东莞",
        "job_state":"",
        "mobile":"13416876676",
        "email":"ziaozhu@qq.com",
        "native":"",
        "house":"",
        "card_num":"",
        "age":49,
        "skill_list":[

        ],
        "intent_job_location":"",
        "intent_salary_type":-1,
        "intent_min_salary":0,
        "intent_max_salary":0,
        "intent_job":"",
        "intent_com":"",
        "intent_power":"",
        "work_year":"10年以上",
        "work_year_code":11,
        "dimission_period":"",
        "work_is_job":"否",
        "work_com_name":"十一月十四",
        "work_com_id":{
            "$oid":"5beb8a98e13823665c7b7eb3"
        },
        "work_address":"广东省-深圳市-罗湖区",
        "work_industry":"",
        "work_industry_level":"",
        "work_position":"电话",
        "work_position_level":"",
        "work_salary_type":"",
        "work_salary":"",
        "project_name":"",
        "education_degree":"中专",
        "education_degree_code":3,
        "education_school":"河源职业技术学院",
        "education_major":"机电一体化",
        "education_is_read":"否",
        "education_is_full_time":"否",
        "education_school_is_985":"",
        "education_school_is_211":"",
        "train_school":"",
        "train_course":"",
        "marriage":"未婚",
        "couple_position":"",
        "couple_com":"",
        "children":"",
        "relation_time":"",
        "relation_time_int":0,
        "edit_time":"2019-05-22",
        "edit_time_int":1558540210,
        "remark_list_name":"",
        "position_action":"未加入",
        "position_action_code":"",
        "position_action_list":[

        ],
        "team_position_action":"未加入",
        "team_position_action_code":"",
        "team_position_action_list":"",
        "my_position_action":"未加入",
        "my_position_action_code":"",
        "my_position_action_list":"",
        "my_order":"",
        "my_position":"",
        "create_type":"",
        "add_time":"2018-11-06",
        "create_user":"蒋家增",
        "create_email":"",
        "look_time":"",
        "is_look":0,
        "attention_time":"",
        "attention":0,
        "work_list":[
            {
                "begin":"2018-11",
                "end":"至今",
                "com_name":"十一月十四",
                "department":"十里香",
                "position":"电话",
                "position_level":0,
                "work_address":"广东省-深圳市-罗湖区",
                "work_address_code":14020100,
                "description":"",
                "salary_type":"",
                "salary":"",
                "salary_detail":"",
                "salary_pay":"",
                "industry":null,
                "industry_code":1,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":null,
                "com_type":null,
                "com_type_code":6,
                "quit_reason":"",
                "attach_file":[

                ]
            }
        ],
        "education_list":[
            {
                "begin":"2003-09",
                "end":"2006-07",
                "degree":"中专",
                "degree_code":3,
                "school":"河源职业技术学院",
                "major":"机电一体化",
                "major_desc":"联系方式联系方式134 1687 6676 (手机) 广东 东莞邮箱ziaozhu@qq.com无",
                "is_full_time":0,
                "attach_file":[

                ]
            }
        ],
        "train_list":[

        ],
        "project_list":[

        ],
        "work_salary_str":"",
        "intent_salary_str":""
    },
    {
        "_id":{
            "$oid":"5be00e7e94ca745e47a0d4ae"
        },
        "name":"李伟兴",
        "bad_record":0,
        "bad_record_list":[

        ],
        "tag_list":[

        ],
        "gender":"男",
        "location":"广东-惠州",
        "job_state":"现状稳定",
        "mobile":"15816890123",
        "email":"979911236@qq.com",
        "native":"",
        "house":"",
        "card_num":"",
        "age":25,
        "skill_list":[

        ],
        "intent_job_location":"",
        "intent_salary_type":1,
        "intent_min_salary":150000,
        "intent_max_salary":250000,
        "intent_job":"仓库管理员",
        "intent_com":"",
        "intent_power":"",
        "work_year":"1年",
        "work_year_code":1,
        "dimission_period":"",
        "work_is_job":"是",
        "work_com_name":"十月二十五",
        "work_com_id":{
            "$oid":"5bd15a2be138236e7c49eb90"
        },
        "work_address":"广东-深圳-福田区",
        "work_industry":"互联网/电子商务",
        "work_industry_level":"",
        "work_position":"猫和老鼠",
        "work_position_level":"",
        "work_salary_type":1,
        "work_salary":200000,
        "project_name":"",
        "education_degree":"高中",
        "education_degree_code":2,
        "education_school":"塘角学校",
        "education_major":"",
        "education_is_read":"否",
        "education_is_full_time":"否",
        "education_school_is_985":"",
        "education_school_is_211":"",
        "train_school":"",
        "train_course":"",
        "marriage":"未婚",
        "couple_position":"",
        "couple_com":"",
        "children":"",
        "relation_time":"2019-04-30",
        "relation_time_int":1556553600,
        "edit_time":"2019-05-27",
        "edit_time_int":1558941380,
        "remark_list_name":"",
        "position_action":"未加入",
        "position_action_code":"",
        "position_action_list":[

        ],
        "team_position_action":"未加入",
        "team_position_action_code":"",
        "team_position_action_list":"",
        "my_position_action":"未加入",
        "my_position_action_code":"",
        "my_position_action_list":"",
        "my_order":"",
        "my_position":"",
        "create_type":"",
        "add_time":"2018-11-06",
        "create_user":"蒋家增",
        "create_email":"",
        "look_time":"2019-05-27",
        "is_look":1,
        "attention_time":"",
        "attention":0,
        "work_list":[
            {
                "begin":"2018-11",
                "end":"",
                "com_name":"十月二十五",
                "industry":"互联网/电子商务",
                "industry_code":1,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"",
                "com_type_code":"",
                "com_type":"",
                "department":"动漫部",
                "position":"猫和老鼠",
                "is_job":1,
                "position_level":"",
                "description":"",
                "quit_reason":"",
                "work_address":"广东-深圳-福田区",
                "work_address_code":14020200,
                "salary_type":1,
                "salary":200000,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2017-03",
                "end":"2018-09-01",
                "com_name":"亚太表业有限公司",
                "industry":"",
                "industry_code":"",
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"",
                "com_type_code":"",
                "com_type":"",
                "department":"",
                "position":"仓库管理员",
                "is_job":0,
                "position_level":"",
                "description":"描 述: 管理仓库的日常工作,以及收发货物",
                "quit_reason":"",
                "work_address":"",
                "work_address_code":"",
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            }
        ],
        "education_list":[
            {
                "begin":"2009-02",
                "end":"2011-07-01",
                "degree":"高中",
                "degree_code":2,
                "school":"塘角学校",
                "major":"",
                "major_desc":"联系方式联系方式130 4686 8918 (手机) 广东 东莞邮箱979919544@qq.com无",
                "is_full_time":0,
                "attach_file":[

                ]
            }
        ],
        "train_list":[

        ],
        "project_list":[

        ],
        "work_salary_str":"200000（年薪）",
        "intent_salary_str":"150000-250000（年薪）",
    },
    {
        "_id":{
            "$oid":"5be1045094ca745e47a0d4db"
        },
        "name":"杨晓",
        "bad_record":0,
        "bad_record_list":[

        ],
        "tag_list":[

        ],
        "gender":"女",
        "location":"广东-深圳-福田区",
        "job_state":"离职看机会",
        "mobile":"13413413412",
        "email":"2519273533@qq.com",
        "native":"广东-深圳-罗湖区",
        "house":"广东-深圳-罗湖区",
        "card_num":"440981199208082220",
        "age":26,
        "skill_list":[
            {
                "date":"2017-11-01",
                "name":"大学英语六级",
                "level":"大学英语六级",
                "attach_file":[
                    {
                        "file_name":"201811\ac37bdd8-e18e-11e8-a65c-000c29ccfccf.jpg",
                        "upload_name":"1541142762(1).jpg",
                        "upload_time":"2018-11-06 14:39:21",
                        "upload_user":"rpo5635"
                    }
                ]
            }
        ],
        "intent_job_location":"广东-深圳-福田区",
        "intent_salary_type":1,
        "intent_min_salary":250000,
        "intent_max_salary":350000,
        "intent_job":"设计总监",
        "intent_com":"中国移动 中国电信 中国联通",
        "intent_power":"dafhbabg",
        "work_year":"4年",
        "work_year_code":4,
        "dimission_period":"2周",
        "work_is_job":"是",
        "work_com_name":"平安金融",
        "work_com_id":"",
        "work_address":"广东-深圳-福田区",
        "work_industry":"计算机软件",
        "work_industry_level":"全国500强",
        "work_position":"设计总监",
        "work_position_level":"",
        "work_salary_type":0,
        "work_salary":"",
        "project_name":"电信传奇",
        "education_degree":"硕士",
        "education_degree_code":6,
        "education_school":"深圳大学",
        "education_major":"计算机工程",
        "education_is_read":"是",
        "education_is_full_time":"否",
        "education_school_is_985":"",
        "education_school_is_211":"",
        "train_school":"尚德教育",
        "train_course":"交互管理",
        "marriage":"未婚",
        "couple_position":"配偶职业",
        "couple_com":"所在单位",
        "children":1,
        "relation_time":"",
        "relation_time_int":0,
        "edit_time":"2019-05-21",
        "edit_time_int":1558428451,
        "remark_list_name":"",
        "position_action":"未加入",
        "position_action_code":"",
        "position_action_list":[

        ],
        "team_position_action":"未加入",
        "team_position_action_code":"",
        "team_position_action_list":"",
        "my_position_action":"未加入",
        "my_position_action_code":"",
        "my_position_action_list":"",
        "my_order":"",
        "my_position":"",
        "create_type":"",
        "add_time":"2018-11-06",
        "create_user":null,
        "create_email":"",
        "look_time":"",
        "is_look":0,
        "attention_time":"",
        "attention":0,
        "work_list":[
            {
                "begin":"2018-11",
                "end":"",
                "com_name":"平安金融",
                "industry":"计算机软件",
                "industry_code":2,
                "industry_level":"全国500强",
                "industry_level_code":6,
                "com_scale":"",
                "com_type_code":"",
                "com_type":"",
                "department":"",
                "position":"设计总监",
                "position_level":"",
                "description":"设计师",
                "quit_reason":"广东-深圳-福田区",
                "work_address":"广东-深圳-福田区",
                "work_address_code":14020200,
                "salary_type":0,
                "salary":0,
                "salary_detail":"adhba",
                "salary_pay":"agagb",
                "attach_file":[
                    {
                        "file_name":"201811\f6957f62-e18e-11e8-a2bd-000c29ccfccf.jpg",
                        "upload_name":"10.jpg",
                        "upload_time":"2018-11-06 14:41:26",
                        "upload_user":"rpo5635"
                    }
                ]
            },
            {
                "begin":"2018-11",
                "end":"",
                "com_name":"深圳丹晴科技有限公司",
                "industry":"互联网/电子商务",
                "industry_code":1,
                "industry_level":"上市",
                "industry_level_code":5,
                "com_scale":"",
                "com_type_code":5,
                "com_type":"",
                "department":"研发部",
                "position":"设计师",
                "position_level":4,
                "description":"aga",
                "quit_reason":"广东-深圳-福田区",
                "work_address":"广东-深圳-福田区",
                "work_address_code":14020200,
                "salary_type":1,
                "salary":300000,
                "salary_detail":"aga",
                "salary_pay":"agag",
                "attach_file":[]
            }
        ],
        "education_list":[
            {
                "begin":"2018-01",
                "end":"",
                "degree":"硕士",
                "degree_code":6,
                "school":"深圳大学",
                "major":"计算机工程",
                "major_desc":"",
                "is_full_time":1,
                "attach_file":[
                    
                ]
            }
        ],
        "train_list":[
            {
                "begin":"2018-01",
                "end":"",
                "school":"尚德教育",
                "address_code":14020200,
                "address":"广东-深圳-福田区",
                "course":"交互管理",
                "certificate":"交互管理顾问",
                "description":"dfbda"
            }
        ],
        "project_list":[
            {
                "begin":"2018-01",
                "end":"",
                "pro_name":"电信传奇",
                "pro_describe":"",
                "duty_describe":"adgfagb",
                "is_leader":1,
                "is_progress":1
            }
        ],
        "work_salary_str":"",
        "intent_salary_str":"250000-350000（年薪）",
    },
    {
        "_id":{
            "$oid":"5be106075dbd0988242b3900"
        },
        "name":"赵志伟",
        "bad_record":0,
        "bad_record_list":[

        ],
        "tag_list":[

        ],
        "gender":"男",
        "location":"北京-西城区",
        "job_state":"短期有意离职看机会",
        "mobile":"15300263757",
        "email":"zzwuisjs@sina.com",
        "native":"广东-广州-天河区",
        "house":"广东-广州-天河区",
        "card_num":"",
        "age":49,
        "skill_list":[
            {
                "date":"2018-12-22",
                "name":"英语",
                "level":"一般",
                "attach_file":[

                ]
            }
        ],
        "intent_job_location":"",
        "intent_salary_type":-1,
        "intent_min_salary":0,
        "intent_max_salary":0,
        "intent_job":"",
        "intent_com":"",
        "intent_power":"",
        "work_year":"3年",
        "work_year_code":3,
        "dimission_period":"",
        "work_is_job":"是",
        "work_com_name":"下雨的第三天",
        "work_com_id":"",
        "work_address":"上海市-上海市-黄浦区",
        "work_industry":"",
        "work_industry_level":"",
        "work_position":"分安慰是",
        "work_position_level":"",
        "work_salary_type":0,
        "work_salary":"",
        "project_name":"朝龙五金网后台",
        "education_degree":"本科",
        "education_degree_code":5,
        "education_school":"山西信息科技学院",
        "education_major":"",
        "education_is_read":"否",
        "education_is_full_time":"否",
        "education_school_is_985":"",
        "education_school_is_211":"",
        "train_school":"",
        "train_course":"",
        "marriage":"未婚",
        "couple_position":"",
        "couple_com":"",
        "children":"",
        "relation_time":"2019-05-20",
        "relation_time_int":1558281600,
        "edit_time":"2019-05-20",
        "edit_time_int":1558360333,
        "remark_list_name":"",
        "position_action":"未加入",
        "position_action_code":"",
        "position_action_list":[

        ],
        "team_position_action":"未加入",
        "team_position_action_code":"",
        "team_position_action_list":"",
        "my_position_action":"未加入",
        "my_position_action_code":"",
        "my_position_action_list":"",
        "my_order":"",
        "my_position":"",
        "create_type":"",
        "add_time":"2018-11-06",
        "create_user":"宁佐飞",
        "create_email":"",
        "look_time":"2019-05-05",
        "is_look":1,
        "attention_time":"",
        "attention":0,
        "work_list":[
            {
                "begin":"2018-11",
                "end":"",
                "com_name":"下雨的第三天",
                "industry":"",
                "industry_code":2,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"",
                "com_type_code":0,
                "com_type":"",
                "department":"",
                "position":"分安慰是",
                "is_job":1,
                "position_level":"",
                "description":"",
                "quit_reason":"",
                "work_address":"上海市-上海市-黄浦区",
                "work_address_code":10000100,
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2014-12",
                "end":"2015-11",
                "com_name":"",
                "industry":"互联网/电子商务",
                "industry_code":"",
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"",
                "com_type_code":"",
                "com_type":"",
                "department":"",
                "position":"设计",
                "is_job":0,
                "position_level":"",
                "description":"1、前期,配合产品经理进行产品需求分析,包括用户需求,市场调研,竞品分析,功能模块分析;2、配合产品经理进行功能模块分析,提出最佳的交互解决方案,进行评审,不断优化方案,版本迭代;3、根据低保真交互原型图出最佳高保真视觉方案,进行评审,不断优化,最终符合用户或客户的需求;4、最后,配合开发团队进行前端制作,最终完成整个产品前端开发流程,不断跟踪优化调试,使产品更加完善,最终符合市场,符合用户的心理需求。",
                "quit_reason":"",
                "work_address":"",
                "work_address_code":"",
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2012-10",
                "end":"2014-12",
                "com_name":"北京极网商业互联技术有限公司(东南融通集团)",
                "industry":"其他",
                "industry_code":"",
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"100-499人",
                "com_type_code":"",
                "com_type":"民营",
                "department":"",
                "position":"视觉设计",
                "is_job":0,
                "position_level":"",
                "description":"1、前期,配合产品经理进行产品需求分析,包括用户需求,市场调研,竞品分析,功能模块分析;2、配合产品经理进行功能模块分析,提出最佳的交互解决方案,进行评审,不断优化方案,版本迭代;3、根据低保真交互原型图设计出最佳高保真视觉方案,进行评审,不断优化,最终符合用户或客户的需求;4、最后,配合开发团队进行前端制作,最终完成整个产品前端开发流程,不断跟踪优化调试,使产品更加完善,最终符合市场,符合用户的心理需求。",
                "quit_reason":"",
                "work_address":"",
                "work_address_code":"",
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            }
        ],
        "education_list":[
            {
                "begin":"2008-09",
                "end":"2012-06",
                "degree":"本科",
                "degree_code":5,
                "school":"山西信息科技学院",
                "major":"",
                "major_desc":"视觉传达",
                "is_full_time":0,
                "attach_file":[

                ]
            }
        ],
        "train_list":[

        ],
        "project_list":[
            {
                "begin":"2015-08",
                "end":"2015-09",
                "pro_name":"朝龙五金网后台",
                "pro_describe":"朝龙五金基本功能控制。主要模块有 用户管理,结算管理、展位管理、商家管理、系统管理等.",
                "duty_describe":"1. 绘制低保真原型图;2 负责所有界面的设计",
                "is_leader":0,
                "is_progress":0
            },
            {
                "begin":"2015-06",
                "end":"2015-08",
                "pro_name":"朝龙五金网",
                "pro_describe":"基于朝龙五金机电市场网重新制作改版,增加支付能、商铺推荐功能功能、二手交易平台、由原有的官网形式,改版商城形式,形成工业电商网。从线下到线上让用户更加方便快捷的购买。体设计以扁平化呈现,",
                "duty_describe":". 参与前期的产品分析(包括市场分析、用户心理调研、功能分析、竞品分析等);2. 根据产品分析的结果制定产品需求文档;3. 参与交互设计流程;4. 绘制低保真原型图;5. 负责所有界面的设计(包括icon、启动界面、欢迎界面等的设计及优化);",
                "is_leader":0,
                "is_progress":0
            },
            {
                "begin":"2015-04",
                "end":"2015-05",
                "pro_name":"大狗商场技术资料",
                "pro_describe":"为用户提供便捷的产品资料查询,百科等",
                "duty_describe":"1.根据产品分析的结果制定产品需求文档;2. 参与交互设计流程;3. 绘制低保真原型图;4. 负责所有界面的设计",
                "is_leader":0,
                "is_progress":0
            },
            {
                "begin":"2014-10",
                "end":"2014-12",
                "pro_name":"时间银行(APP)",
                "pro_describe":"本应用宗旨在传递“互帮互助”、有爱奉献的志愿者服务精神,集结各类公益信息、对接各类公益活动或公益或公益项目公众平台,“求助者”可根据自身情况发布求助信息,接受他人帮助。“志愿者”可时跟进多样化的求助信息。根据自身情况自主对接参与志愿服务,并自动累计服务时长,产于海都公众设立“爱心兑换”实现爱心升值、变现。同时时间银行还综合物资捐赠、爱心捐赠等方式。实现志愿的多样化。",
                "duty_describe":"参与前期的产品分析(包括市场分析、用户心理调研、功能分析、竞品分析等);2. 根据产品分析的结果制定产品需求文档;3. 参与交互设计流程;4. 负责所有界面的设计(包括icon、启动界面、欢迎界面等的设计及优化);5. 根据用户反馈信息对界面和交互进行修改和进一步的优化;",
                "is_leader":0,
                "is_progress":0
            },
            {
                "begin":"2014-06",
                "end":"2014-08",
                "pro_name":"园区宝App项目",
                "pro_describe":"园区宝是一款新思维构建服务平台,微生态培育智慧的园区,功能主要有:吃喝玩乐购,海量商品信息随时掌控;随手心情,同城活动,一键保修应有尽有;私人定制,轻轻松松出行。",
                "duty_describe":"1. 参与前期的产品分析(包括市场分析、用户心理调研、功能分析、竞品分析等);2. 根据产品分析的结果制定产品需求文档;3. 参与交互设计流程;4. 负责所有界面的设计(包括icon、启动界面、欢迎界面等的设计及优化);5. 根据用户反馈信息对界面和交互进行修改和进一步的优化;",
                "is_leader":0,
                "is_progress":0
            },
            {
                "begin":"2013-11",
                "end":"2014-02",
                "pro_name":"农业银行项目",
                "pro_describe":"该软件为用户提供了掌上即使申请贷款的业务,安全便捷;享受分分钟放款,流程;随时随地获取最新消息,极大的方便用户第一时间获取资料。",
                "duty_describe":"1. 参与交互设计流程;2. 负责界面的设计",
                "is_leader":0,
                "is_progress":0
            }
        ],
        "work_salary_str":"",
        "intent_salary_str":""
    },
    {
        "_id":{
            "$oid":"5be12e9c94ca745e47a0d4e2"
        },
        "name":"李星云",
        "bad_record":0,
        "bad_record_list":[

        ],
        "tag_list":[

        ],
        "gender":"男",
        "location":"广东-深圳-福田区",
        "job_state":"在职看机会",
        "mobile":"13413432342",
        "email":"2519273533@qq.com",
        "native":"",
        "house":null,
        "card_num":"",
        "age":49,
        "skill_list":[

        ],
        "intent_job_location":"",
        "intent_salary_type":"",
        "intent_min_salary":"",
        "intent_max_salary":"",
        "intent_job":"",
        "intent_com":"",
        "intent_power":"",
        "work_year":"5年",
        "work_year_code":5,
        "dimission_period":"",
        "work_is_job":"否",
        "work_com_name":"上海旺旺食品集团有限公司",
        "work_com_id":{
            "$oid":"5bd2b25ae138236dfd4a466c"
        },
        "work_address":"广东省-深圳市-深圳市",
        "work_industry":"",
        "work_industry_level":"",
        "work_position":"项目经理",
        "work_position_level":"",
        "work_salary_type":"",
        "work_salary":"",
        "project_name":"",
        "education_degree":"MBA",
        "education_degree_code":7,
        "education_school":"",
        "education_major":"",
        "education_is_read":"",
        "education_is_full_time":"",
        "education_school_is_985":"",
        "education_school_is_211":"",
        "train_school":"",
        "train_course":"",
        "marriage":"未婚",
        "couple_position":"",
        "couple_com":"",
        "children":"",
        "relation_time":"",
        "relation_time_int":0,
        "edit_time":"2019-05-20",
        "edit_time_int":1558360333,
        "remark_list_name":"",
        "position_action":"未加入",
        "position_action_code":"",
        "position_action_list":[

        ],
        "team_position_action":"未加入",
        "team_position_action_code":"",
        "team_position_action_list":"",
        "my_position_action":"未加入",
        "my_position_action_code":"",
        "my_position_action_list":"",
        "my_order":"",
        "my_position":"",
        "create_type":"",
        "add_time":"2018-11-06",
        "create_user":null,
        "create_email":"",
        "look_time":"",
        "is_look":0,
        "attention_time":"",
        "attention":0,
        "work_list":[
            {
                "begin":"2018-12",
                "end":"至今",
                "com_name":"上海旺旺食品集团有限公司",
                "department":"研发部",
                "position":"项目经理",
                "position_level":0,
                "work_address":"广东省-深圳市-深圳市",
                "work_address_code":14020000,
                "description":"",
                "salary_type":"",
                "salary":"",
                "salary_detail":"",
                "salary_pay":"",
                "industry":null,
                "industry_code":3,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":null,
                "com_type":null,
                "com_type_code":3,
                "quit_reason":"",
                "attach_file":[

                ]
            },
            {
                "begin":"",
                "end":"",
                "com_name":"中国电信",
                "industry":"",
                "industry_code":"",
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"",
                "com_type_code":"",
                "com_type":"",
                "department":"",
                "position":"",
                "position_level":"",
                "description":"技术总监督",
                "quit_reason":"",
                "work_address":"",
                "work_address_code":"",
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            }
        ],
        "education_list":[

        ],
        "train_list":"",
        "project_list":"",
        "work_salary_str":"",
        "intent_salary_str":""
    },
    {
        "_id":{
            "$oid":"5be13f2294ca745e47a0d4eb"
        },
        "name":"董玲",
        "bad_record":0,
        "bad_record_list":[

        ],
        "tag_list":[

        ],
        "gender":"女",
        "location":"广东-广州-海珠区",
        "job_state":"短期有意离职看机会",
        "mobile":"13434123421",
        "email":"2519273533@qq.com",
        "native":"",
        "house":null,
        "card_num":"",
        "age":49,
        "skill_list":[

        ],
        "intent_job_location":"",
        "intent_salary_type":"",
        "intent_min_salary":"",
        "intent_max_salary":"",
        "intent_job":"",
        "intent_com":"",
        "intent_power":"",
        "work_year":"5年",
        "work_year_code":5,
        "dimission_period":"",
        "work_is_job":"否",
        "work_com_name":"上海旺旺食品集团有限公司",
        "work_com_id":{
            "$oid":"5bd2b25ae138236dfd4a466c"
        },
        "work_address":"广东省-深圳市-深圳市",
        "work_industry":"",
        "work_industry_level":"",
        "work_position":"项目经理",
        "work_position_level":"",
        "work_salary_type":"",
        "work_salary":"",
        "project_name":"",
        "education_degree":"硕士",
        "education_degree_code":6,
        "education_school":"",
        "education_major":"",
        "education_is_read":"",
        "education_is_full_time":"",
        "education_school_is_985":"",
        "education_school_is_211":"",
        "train_school":"",
        "train_course":"",
        "marriage":"未婚",
        "couple_position":"",
        "couple_com":"",
        "children":"",
        "relation_time":"",
        "relation_time_int":0,
        "edit_time":"2019-05-20",
        "edit_time_int":1558360333,
        "remark_list_name":"",
        "position_action":"未加入",
        "position_action_code":"",
        "position_action_list":[

        ],
        "team_position_action":"未加入",
        "team_position_action_code":"",
        "team_position_action_list":"",
        "my_position_action":"未加入",
        "my_position_action_code":"",
        "my_position_action_list":"",
        "my_order":"",
        "my_position":"",
        "create_type":"",
        "add_time":"2018-11-06",
        "create_user":null,
        "create_email":"",
        "look_time":"",
        "is_look":0,
        "attention_time":"",
        "attention":0,
        "work_list":[
            {
                "begin":"2018-12",
                "end":"至今",
                "com_name":"上海旺旺食品集团有限公司",
                "department":"研发部",
                "position":"项目经理",
                "position_level":0,
                "work_address":"广东省-深圳市-深圳市",
                "work_address_code":14020000,
                "description":"",
                "salary_type":"",
                "salary":"",
                "salary_detail":"",
                "salary_pay":"",
                "industry":null,
                "industry_code":3,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":null,
                "com_type":null,
                "com_type_code":3,
                "quit_reason":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2018-11",
                "end":"",
                "com_name":"深圳丹晴科技有限公司",
                "industry":"",
                "industry_code":1,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"",
                "com_type_code":5,
                "com_type":"",
                "department":"研发部",
                "position":"设计师",
                "position_level":"",
                "description":"",
                "quit_reason":"",
                "work_address":"广东省-深圳市-福田区",
                "work_address_code":14020200,
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            },
            {
                "begin":"",
                "end":"",
                "com_name":"京东金融",
                "industry":"",
                "industry_code":"",
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"",
                "com_type_code":"",
                "com_type":"",
                "department":"",
                "position":"",
                "position_level":"",
                "description":"设计总监",
                "quit_reason":"",
                "work_address":"",
                "work_address_code":"",
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            }
        ],
        "education_list":[

        ],
        "train_list":"",
        "project_list":"",
        "work_salary_str":"",
        "intent_salary_str":""
    },
    {
        "_id":{
            "$oid":"5be142c494ca745e47a0d4ee"
        },
        "name":"张华",
        "bad_record":0,
        "bad_record_list":[

        ],
        "tag_list":[

        ],
        "gender":"男",
        "location":"广东-深圳-福田区",
        "job_state":"现状稳定",
        "mobile":"13426414561",
        "email":"2519273533@qq.com",
        "native":"天津-河东区",
        "house":"北京-东城区",
        "card_num":"440981198804082145",
        "age":31,
        "skill_list":[

        ],
        "intent_job_location":"",
        "intent_salary_type":"",
        "intent_min_salary":"",
        "intent_max_salary":"",
        "intent_job":"",
        "intent_com":"",
        "intent_power":"",
        "work_year":"4年",
        "work_year_code":4,
        "dimission_period":"",
        "work_is_job":"否",
        "work_com_name":"十一月二十九",
        "work_com_id":{
            "$oid":"5bff4a38e1382366a4160863"
        },
        "work_address":"广东省-深圳市-罗湖区",
        "work_industry":"",
        "work_industry_level":"",
        "work_position":"网站测试工程师",
        "work_position_level":"",
        "work_salary_type":"",
        "work_salary":"",
        "project_name":"",
        "education_degree":"硕士",
        "education_degree_code":6,
        "education_school":"DVD",
        "education_major":"计算机工程",
        "education_is_read":"是",
        "education_is_full_time":"否",
        "education_school_is_985":"",
        "education_school_is_211":"",
        "train_school":"",
        "train_course":"",
        "marriage":"未婚",
        "couple_position":"",
        "couple_com":"",
        "children":"",
        "relation_time":"",
        "relation_time_int":0,
        "edit_time":"2019-05-20",
        "edit_time_int":1558360333,
        "remark_list_name":"",
        "position_action":"未加入",
        "position_action_code":"",
        "position_action_list":[

        ],
        "team_position_action":"未加入",
        "team_position_action_code":"",
        "team_position_action_list":"",
        "my_position_action":"未加入",
        "my_position_action_code":"",
        "my_position_action_list":"",
        "my_order":"",
        "my_position":"",
        "create_type":"",
        "add_time":"2018-11-06",
        "create_user":null,
        "create_email":"",
        "look_time":"",
        "is_look":0,
        "attention_time":"",
        "attention":0,
        "work_list":[
            {
                "begin":"2018-11",
                "end":"至今",
                "com_name":"十一月二十九",
                "department":"深圳工程师",
                "position":"网站测试工程师",
                "position_level":0,
                "work_address":"广东省-深圳市-罗湖区",
                "work_address_code":14020100,
                "description":"",
                "salary_type":"",
                "salary":"",
                "salary_detail":"",
                "salary_pay":"",
                "industry":null,
                "industry_code":1,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":null,
                "com_type":null,
                "com_type_code":0,
                "quit_reason":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2018-11",
                "end":"",
                "com_name":"中国移动",
                "industry":"计算机软件",
                "industry_code":2,
                "industry_level":"领先",
                "industry_level_code":4,
                "com_scale":"",
                "com_type_code":"",
                "com_type":"",
                "department":"",
                "position":"别的",
                "position_level":4,
                "description":"设计师",
                "quit_reason":"",
                "work_address":"天津-河东区",
                "work_address_code":12000200,
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            }
        ],
        "education_list":[
            {
                "begin":"2018-01",
                "end":"",
                "degree":"硕士",
                "degree_code":6,
                "school":"DVD",
                "major":"计算机工程",
                "major_desc":"",
                "is_full_time":1,
                "attach_file":[

                ]
            }
        ],
        "train_list":[

        ],
        "project_list":[

        ],
        "work_salary_str":"",
        "intent_salary_str":""
    },
    {
        "_id":{
            "$oid":"5be144a894ca745e47a0d4f1"
        },
        "name":"黄军",
        "bad_record":0,
        "bad_record_list":[

        ],
        "tag_list":[

        ],
        "gender":"男",
        "location":"广东-珠海-斗门区",
        "job_state":"现状稳定",
        "mobile":"13464456415",
        "email":"2519273533@qq.com",
        "native":"",
        "house":null,
        "card_num":"",
        "age":49,
        "skill_list":[

        ],
        "intent_job_location":"",
        "intent_salary_type":"",
        "intent_min_salary":"",
        "intent_max_salary":"",
        "intent_job":"",
        "intent_com":"",
        "intent_power":"",
        "work_year":"4年",
        "work_year_code":4,
        "dimission_period":"",
        "work_is_job":"否",
        "work_com_name":"好公司一",
        "work_com_id":{
            "$oid":"5bd6e4f6e138236e7124c765"
        },
        "work_address":"上海市-上海市-黄浦区",
        "work_industry":"",
        "work_industry_level":"",
        "work_position":"新岗位",
        "work_position_level":"",
        "work_salary_type":"",
        "work_salary":"",
        "project_name":"",
        "education_degree":"本科",
        "education_degree_code":5,
        "education_school":"",
        "education_major":"",
        "education_is_read":"",
        "education_is_full_time":"",
        "education_school_is_985":"",
        "education_school_is_211":"",
        "train_school":"",
        "train_course":"",
        "marriage":"未婚",
        "couple_position":"",
        "couple_com":"",
        "children":"",
        "relation_time":"",
        "relation_time_int":0,
        "edit_time":"2019-05-20",
        "edit_time_int":1558360333,
        "remark_list_name":"",
        "position_action":"未加入",
        "position_action_code":"",
        "position_action_list":[

        ],
        "team_position_action":"未加入",
        "team_position_action_code":"",
        "team_position_action_list":"",
        "my_position_action":"未加入",
        "my_position_action_code":"",
        "my_position_action_list":"",
        "my_order":"",
        "my_position":"",
        "create_type":"",
        "add_time":"2018-11-06",
        "create_user":null,
        "create_email":"",
        "look_time":"",
        "is_look":0,
        "attention_time":"",
        "attention":0,
        "work_list":[
            {
                "begin":"2018-11",
                "end":"至今",
                "com_name":"好公司一",
                "department":"",
                "position":"新岗位",
                "position_level":0,
                "work_address":"上海市-上海市-黄浦区",
                "work_address_code":10000100,
                "description":"",
                "salary_type":"",
                "salary":"",
                "salary_detail":"",
                "salary_pay":"",
                "industry":null,
                "industry_code":1,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":null,
                "com_type":null,
                "com_type_code":3,
                "quit_reason":"",
                "attach_file":[

                ]
            },
            {
                "begin":"2018-11",
                "end":"",
                "com_name":"中山市广弘集团有限公司",
                "industry":"",
                "industry_code":38,
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"",
                "com_type_code":6,
                "com_type":"",
                "department":"研发部",
                "position":"项目经理",
                "position_level":"",
                "description":"",
                "quit_reason":"",
                "work_address":"广东省-深圳市-福田区",
                "work_address_code":14020200,
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            },
            {
                "begin":"",
                "end":"",
                "com_name":"大疆技术有限公司",
                "industry":"",
                "industry_code":"",
                "industry_level":"",
                "industry_level_code":"",
                "com_scale":"",
                "com_type_code":"",
                "com_type":"",
                "department":"",
                "position":"",
                "position_level":"",
                "description":"设计师",
                "quit_reason":"",
                "work_address":"",
                "work_address_code":"",
                "salary_type":0,
                "salary":0,
                "salary_detail":"",
                "salary_pay":"",
                "attach_file":[

                ]
            }
        ],
        "education_list":[

        ],
        "train_list":"",
        "project_list":"",
        "work_salary_str":"",
        "intent_salary_str":""
    }
]
    }
  }
}
</script>

<style>
</style>
